runtime: python
env: flex
entrypoint: gunicorn -b :8080 runServer:app
runtime_config:
  python_version: 3.7

env_variables:
  CLOUD_SQL_CONNECTION_NAME: nathancapstone2021-296406:us-central1:nathancapstone-sqldatabase-2021
  DB_USER: root
  DB_PASS: rp1prekOdA5z0fym
  DB_NAME: capstone_db
  CLOUDSQL_USER: root
  CLOUDSQL_PASSWORD: rp1prekOdA5z0fym
  CLOUD_APP: AppEngine
  CLOUD_STORAGE_BUCKET: nathancapstone2021-296406.appspot.com

beta_settings:
    cloud_sql_instances: nathancapstone2021-296406:us-central1:nathancapstone-sqldatabase-2021

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10