"""added Study table

Revision ID: 3ab7c45e4ac3
Revises: fff6d0bd8c90
Create Date: 2021-01-22 14:11:34.858947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ab7c45e4ac3'
down_revision = 'fff6d0bd8c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subtopic_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('study', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('alembic_version_copy1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version_copy1',
    sa.Column('version_num', mysql.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('version_num'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_texts')
    # ### end Alembic commands ###
