"""userrole added for user

Revision ID: be6bb1962a16
Revises: d343adbef0f1
Create Date: 2021-01-14 09:40:40.004010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be6bb1962a16'
down_revision = 'd343adbef0f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('userrole', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'userrole')
    # ### end Alembic commands ###
