"""question table insert

Revision ID: d17ec6dd7f21
Revises: be6bb1962a16
Create Date: 2021-01-15 08:24:16.997613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd17ec6dd7f21'
down_revision = 'be6bb1962a16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(length=256), nullable=True),
    sa.Column('id_course', sa.Integer(), nullable=True),
    sa.Column('id_topic', sa.Integer(), nullable=True),
    sa.Column('id_subtopic', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('answer1', sa.String(length=256), nullable=True),
    sa.Column('answer2', sa.String(length=256), nullable=True),
    sa.Column('answer3', sa.String(length=256), nullable=True),
    sa.Column('answer4', sa.String(length=256), nullable=True),
    sa.Column('question_number', sa.Integer(), nullable=True),
    sa.Column('correct_answer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_course'], ['course.id'], ),
    sa.ForeignKeyConstraint(['id_subtopic'], ['subtopic.id'], ),
    sa.ForeignKeyConstraint(['id_topic'], ['topic.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_question'), 'question', ['question'], unique=False)
    op.add_column('subtopic', sa.Column('question_count', sa.Integer(), nullable=True))
    op.drop_index('ix_subtopic_correct_answer', table_name='subtopic')
    op.drop_index('ix_subtopic_img_url_answers', table_name='subtopic')
    op.drop_index('ix_subtopic_img_url_question', table_name='subtopic')
    op.drop_column('subtopic', 'img_url_answers')
    op.drop_column('subtopic', 'img_url_question')
    op.drop_column('subtopic', 'correct_answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtopic', sa.Column('correct_answer', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('subtopic', sa.Column('img_url_question', mysql.VARCHAR(length=512), nullable=True))
    op.add_column('subtopic', sa.Column('img_url_answers', mysql.VARCHAR(length=2048), nullable=True))
    op.create_index('ix_subtopic_img_url_question', 'subtopic', ['img_url_question'], unique=False)
    op.create_index('ix_subtopic_img_url_answers', 'subtopic', ['img_url_answers'], unique=False)
    op.create_index('ix_subtopic_correct_answer', 'subtopic', ['correct_answer'], unique=False)
    op.drop_column('subtopic', 'question_count')
    op.drop_index(op.f('ix_question_question'), table_name='question')
    op.drop_table('question')
    # ### end Alembic commands ###
