"""Initial migration

Revision ID: d343adbef0f1
Revises: 
Create Date: 2021-01-13 23:40:36.204802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd343adbef0f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_title'), 'course', ['title'], unique=False)
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('id_course', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_course'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_title'), 'topic', ['title'], unique=False)
    op.create_table('subtopic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('id_course', sa.Integer(), nullable=True),
    sa.Column('id_topic', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('img_url_question', sa.String(length=512), nullable=True),
    sa.Column('img_url_answers', sa.String(length=2048), nullable=True),
    sa.Column('correct_answer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_course'], ['course.id'], ),
    sa.ForeignKeyConstraint(['id_topic'], ['topic.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtopic_correct_answer'), 'subtopic', ['correct_answer'], unique=False)
    op.create_index(op.f('ix_subtopic_img_url_answers'), 'subtopic', ['img_url_answers'], unique=False)
    op.create_index(op.f('ix_subtopic_img_url_question'), 'subtopic', ['img_url_question'], unique=False)
    op.create_index(op.f('ix_subtopic_title'), 'subtopic', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subtopic_title'), table_name='subtopic')
    op.drop_index(op.f('ix_subtopic_img_url_question'), table_name='subtopic')
    op.drop_index(op.f('ix_subtopic_img_url_answers'), table_name='subtopic')
    op.drop_index(op.f('ix_subtopic_correct_answer'), table_name='subtopic')
    op.drop_table('subtopic')
    op.drop_index(op.f('ix_topic_title'), table_name='topic')
    op.drop_table('topic')
    op.drop_index(op.f('ix_course_title'), table_name='course')
    op.drop_table('course')
    op.drop_table('user')
    # ### end Alembic commands ###
