"""modify fields for TestResult table

Revision ID: fff6d0bd8c90
Revises: b269806e38f6
Create Date: 2021-01-17 07:03:59.497890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff6d0bd8c90'
down_revision = 'b269806e38f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_course', sa.Integer(), nullable=True),
    sa.Column('id_topic', sa.Integer(), nullable=True),
    sa.Column('id_subtopic', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=True),
    sa.Column('answers', sa.String(length=256), nullable=True),
    sa.Column('correct_answers', sa.String(length=256), nullable=True),
    sa.Column('is_correct', sa.String(length=256), nullable=True),
    sa.Column('show', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_course'], ['course.id'], ),
    sa.ForeignKeyConstraint(['id_subtopic'], ['subtopic.id'], ),
    sa.ForeignKeyConstraint(['id_topic'], ['topic.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_result')
    # ### end Alembic commands ###
